server:
  port: 8761
  error:
    include-message: always
    include-binding-errors: always
  forward-headers-strategy: native

oauth:
  google:
    clientId: ${GOOGLE_OAUTH_CLIENT_ID}
    clientSecret: ${GOOGLE_OAUTH_CLIENT_SECRET}
    scope: "openid profile email"

spring:
  application:
    name: gateway
#  config:
#    import: optional:consul:/
  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        health-check-path: /health
    gateway:
      routes:
        - id: gateway-oauth-route
          uri: lb://gateway
          predicates:
            - Path=/oauth/**
        - id: service-songs-route
          uri: ${service.songs.url}
          predicates:
            - Path=/api/song/**
          filters:
            - RewritePath=/api/song/(?<remaining>.*), /api/song/${remaining}
  data:
    redis:
      repositories:
        enabled: true
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}

resilience4j:
  circuitbreaker:
    instances:
      services:
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 60
        slow-call-duration-threshold:
          - 2s
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 1

frontend:
  url: ${FRONTEND_URL}

service:
  songs:
    url: ${SERVICE_SONGS_ROUTE}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"